name: namida
description: A Beautiful and Feature-rich Music Player, With YouTube & Video Support Built in Flutter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependency_overrides:
  win32: ^3.0.0
  dart_extensions:
    git:
      url: https://github.com/MSOB7YY/dart_extensions
      ref: 4628356a449cdeb12bef5a3a9b4ed37668530192

dependencies:
  flutter:
    sdk: flutter

  # ---- Core ----
  get:
    git:
      url: https://github.com/MSOB7YY/getx
  permission_handler: ^10.4.3
  device_info_plus: ^8.1.0
  intl: ^0.18.0
  flutter_archive: ^5.0.0
  url_launcher: ^6.1.10
  connectivity_plus: ^4.0.2
  selectable_autolink_text: ^2.6.0
  share_plus: ^7.1.0
  readmore: ^2.2.0
  calendar_date_picker2: ^0.5.2
  wakelock_plus: ^1.1.1
  flutter_local_notifications: ^15.1.0
  flutter_sharing_intent:
    git:
      url: https://github.com/MSOB7YY/flutter_sharing_intent
      ref: d1881c5e527db26d2d139edb858b5384f6331405
  catcher:
    git:
      url: https://github.com/MSOB7YY/catcher
  queue: ^3.1.0+2
  jiffy: ^6.2.1
  playlist_manager:
    git:
      url: https://github.com/namidaco/playlist_manager
      ref: 1c1c6e3a0dde1c08f90190de02afcb498b49e173
  history_manager:
    git:
      url: https://github.com/namidaco/history_manager
      ref: fb4f13b536b5cbf61dfd9ef9e29669544247cca1
  flutter_html:
    git:
      url: https://github.com/zhourengui/flutter_html
  picture_in_picture:
    git:
      url: https://github.com/MSOB7YY/picture_in_picture
      ref: 8989afc0e8b854819d79ace61da9b9544ad6068f
  flutter_volume_controller: ^1.2.7
  flutter_markdown: ^0.6.17+3

  # ---- Path/File Providers ----
  path_provider: ^2.0.14
  external_path: ^1.0.3
  file_picker: ^5.3.3

  # ----Audio Indexing & Playback ----
  just_audio: ^0.9.34
  audio_service:
    git:
      url: https://github.com/MSOB7YY/audio_service
      path: audio_service/
      ref: b21b6503c2c4ee39d83c163cfa4cc7b05044e649
  faudiotagger:
    git:
      url: https://github.com/MSOB7YY/faudiotagger
      ref: 454f4357840eebae5c3ec1f91345257c858caf93
  waveform_extractor: ^1.0.1
  basic_audio_handler:
    git:
      url: https://github.com/namidaco/basic_audio_handler
      ref: b7c52ac9c6433b67eb52bb101dced89963c89b61

  # ---- Video Indexing & Playback ----
  video_player:
    git:
      url: https://github.com/MSOB7YY/video_player_cache
      path: video_player/
      ref: ebd92a98f08f92ffa9daa080dcd6796785e12ad7
  ffmpeg_kit_flutter_min: "5.1.0-LTS"
  newpipeextractor_dart:
    git:
      url: https://github.com/MSOB7YY/NewPipeExtractor_Dart
      ref: c9d66d5ac24e385a384038fcc79c15a439283c37

  # ---- Image Utilities ----
  extended_image: ^8.0.2
  palette_generator: ^0.3.3+2
  photo_view: ^0.14.0

  # ---- UI Rendering ----
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_colorpicker: ^1.0.3
  animated_background: ^2.0.0
  known_extents_list_view_builder:
    git:
      url: https://github.com/MSOB7YY/known_extents_listview_fancy
      ref: 95d9e56403b03f2f176bdceb269119d11cf7a4ef
  flutter_animate: ^4.2.0+1
  sticky_and_expandable_list: ^1.1.3

  # ---- UI Widgets ----
  wheel_slider: ^1.0.1
  sleek_circular_slider: ^2.0.1
  checkmark: ^0.0.2+1
  like_button: ^2.0.5
  miniplayer: ^1.0.1
  flutter_scrollbar_modified:
    git:
      url: https://github.com/MSOB7YY/flutter_scrollbar_modified
  sticky_headers: ^0.3.0+2
  focused_menu: ^1.0.5

  # ---- Under Test ----
  # google_sign_in: ^6.0.2
  dio: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  flutter_native_splash:

flutter_native_splash:
  image: assets/namida_icon.png
  image_dark: assets/namida_icon.png
  color: "#dfc6a7"
  color_dark: "#dfc6a7"
  android: true
  ios: false
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/language/langs.json
    - assets/language/translations/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/namida_icon.png
  fonts:
    - family: broken
      fonts:
        - asset: assets/fonts/broken.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf
