# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.ACCESS_TOKEN }}
         submodules: recursive

      - uses: subosito/flutter-action@v2.11.0
        with:
         flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk --split-per-abi

      - name: Upload APKs
        run: |
          mkdir -p artifacts
          mv build/app/outputs/flutter-apk/*.apk artifacts/
        shell: bash

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-releases
          path: artifacts/
